# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_backend', '0006_auto_20210629_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange_backend.Currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange_backend.Currency'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_wallet', to='exchange_backend.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange_backend.Currency'),
        ),
    ]
