# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-02 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_backend', '0007_auto_20210707_0426'),
    ]

    operations = [
    ]
