# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_backend', '0008_auto_20210802_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
